-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2023-10-25 14:33:35 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE Adres
  ( id_adres INTEGER NOT NULL , Grad CHAR (20)
  ) ;
ALTER TABLE Adres ADD CONSTRAINT Adres_PK PRIMARY KEY ( id_adres ) ;


CREATE TABLE Avtomobil
  (
    id_avtomobil INTEGER NOT NULL ,
    Godina       INTEGER ,
    Izminati_km  INTEGER ,
    Cena_na_den  INTEGER ,
    id_cvqt      INTEGER NOT NULL ,
    id_model     INTEGER NOT NULL ,
    id_vid       INTEGER NOT NULL
  ) ;
ALTER TABLE Avtomobil ADD CONSTRAINT Avtomobil_PK PRIMARY KEY ( id_avtomobil ) ;


CREATE TABLE Klient
  (
    id_klient INTEGER NOT NULL ,
    Ime       CHAR (50) ,
    Adres     CHAR (50) ,
    Telefon   INTEGER ,
    id_adres  INTEGER NOT NULL
  ) ;
ALTER TABLE Klient ADD CONSTRAINT Klient_PK PRIMARY KEY ( id_klient ) ;


CREATE TABLE Model
  (
    id_model INTEGER NOT NULL ,
    Model    CHAR (50) ,
    id_marka INTEGER NOT NULL
  ) ;
ALTER TABLE Model ADD CONSTRAINT Model_PK PRIMARY KEY ( id_model ) ;


CREATE TABLE Poziciq
  (
    id_poziciq INTEGER NOT NULL ,
    poziciq    CHAR (50) NOT NULL
  ) ;
ALTER TABLE Poziciq ADD CONSTRAINT Poziciq_PK PRIMARY KEY ( id_poziciq ) ;


CREATE TABLE Relation_16
  (
    Model_id_model INTEGER NOT NULL ,
    vid_id_vid     INTEGER NOT NULL
  ) ;
ALTER TABLE Relation_16 ADD CONSTRAINT Relation_16_PK PRIMARY KEY ( Model_id_model, vid_id_vid ) ;


CREATE TABLE Slujitel
  (
    id_slujitel INTEGER NOT NULL ,
    Ime         CHAR (50) ,
    Poziciq     CHAR (20) ,
    Telefon     INTEGER ,
    id_poziciq  INTEGER NOT NULL
  ) ;
ALTER TABLE Slujitel ADD CONSTRAINT Slujitel_PK PRIMARY KEY ( id_slujitel ) ;


CREATE TABLE cvqt
  ( id_cvqt INTEGER NOT NULL , cvqt CHAR (50) NOT NULL
  ) ;
ALTER TABLE cvqt ADD CONSTRAINT cvqt_PK PRIMARY KEY ( id_cvqt ) ;


CREATE TABLE marka
  ( id_marka INTEGER NOT NULL , marka CHAR (50)
  ) ;
ALTER TABLE marka ADD CONSTRAINT marka_PK PRIMARY KEY ( id_marka ) ;


CREATE TABLE vid
  ( id_vid INTEGER NOT NULL , vid CHAR (50)
  ) ;
ALTER TABLE vid ADD CONSTRAINT vid_PK PRIMARY KEY ( id_vid ) ;


CREATE TABLE zaemane_pod_naem
  (
    id_pod_naem     INTEGER NOT NULL ,
    id_klient       INTEGER NOT NULL ,
    id_slujitel     INTEGER NOT NULL ,
    data_na_zaemane DATE ,
    broi_dni        INTEGER ,
    id_avtomobil    INTEGER NOT NULL
  ) ;
ALTER TABLE zaemane_pod_naem ADD CONSTRAINT zaemane_pod_naem_PK PRIMARY KEY ( id_pod_naem ) ;


ALTER TABLE Avtomobil ADD CONSTRAINT Avtomobil_Model_FK FOREIGN KEY ( id_model ) REFERENCES Model ( id_model ) ;

ALTER TABLE Avtomobil ADD CONSTRAINT Avtomobil_cvqt_FK FOREIGN KEY ( id_cvqt ) REFERENCES cvqt ( id_cvqt ) ;

ALTER TABLE Avtomobil ADD CONSTRAINT Avtomobil_vid_FK FOREIGN KEY ( id_vid ) REFERENCES vid ( id_vid ) ;

ALTER TABLE Relation_16 ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( Model_id_model ) REFERENCES Model ( id_model ) ;

ALTER TABLE Relation_16 ADD CONSTRAINT FK_ASS_3 FOREIGN KEY ( vid_id_vid ) REFERENCES vid ( id_vid ) ;

ALTER TABLE Klient ADD CONSTRAINT Klient_Adres_FK FOREIGN KEY ( id_adres ) REFERENCES Adres ( id_adres ) ;

ALTER TABLE Model ADD CONSTRAINT Model_marka_FK FOREIGN KEY ( id_marka ) REFERENCES marka ( id_marka ) ;

ALTER TABLE Slujitel ADD CONSTRAINT Slujitel_Poziciq_FK FOREIGN KEY ( id_poziciq ) REFERENCES Poziciq ( id_poziciq ) ;

ALTER TABLE zaemane_pod_naem ADD CONSTRAINT zaemane_pod_naem_Avtomobil_FK FOREIGN KEY ( id_avtomobil ) REFERENCES Avtomobil ( id_avtomobil ) ;

ALTER TABLE zaemane_pod_naem ADD CONSTRAINT zaemane_pod_naem_Klient_FK FOREIGN KEY ( id_klient ) REFERENCES Klient ( id_klient ) ;

ALTER TABLE zaemane_pod_naem ADD CONSTRAINT zaemane_pod_naem_Slujitel_FK FOREIGN KEY ( id_slujitel ) REFERENCES Slujitel ( id_slujitel ) ;

create or replace TRIGGER id_poziciq_AUTO_TRG
BEFORE INSERT ON Poziciq
FOR EACH ROW
WHEN (NEW.id_poziciq IS NULL)
BEGIN:NEW.id_pozciq := POS_SEQ.NEXTVAL;
END;
-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
